runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /.*
    script: main.app
    login: required

  - url: /static
    static_dir: style_sheets
 #- url: /static
   #static_dir: static

libraries:
- name: jinja2
  version: latest
